#ifndef mental_types_h
#define mental_types_h

typedef enum MentalResult {
    MENTAL_OK                   =  0,
    MENTAL_UNIMPLEMENTED_ERROR  =  1,
    MENTAL_FATAL_ERROR          = -1,

    MENTAL_VECTOR_POINTER_IS_NULL = -100,
    MENTAL_VECTOR_OUT_OF_MEMORY   = -101,
    MENTAL_VECTOR_UNDERFLOW       = -102,

    MENTAL_VECTOR_INITIALIZED     =  100,
    MENTAL_VECTOR_DESTROYED       =  101,
    MENTAL_VECTOR_ELEMENT_PUSHED_BACK = 102,

    MENTAL_POINTER_IS_NULL    = -200,

    MENTAL_FAILED_TO_ALLOCATE_MEMORY_FOR_MENTAL_WM = -301,

    MENTAL_FAILED_TO_ALLOCATE_MEMORY_FOR_ENGINE = -401,
} MentalResult;

typedef enum MentalStructureType {
    MENTAL_STRUCTURE_TYPE_PROJECT_INFO,
    MENTAL_STRUCTURE_TYPE_PROJECT,

    MENTAL_STRUCTURE_TYPE_WM_INFO,
    MENTAL_STRUCTURE_TYPE_WM,

    MENTAL_STRUCTURE_TYPE_ENGINE_INFO,
    MENTAL_STRUCTURE_TYPE_ENGINE,

    MENTAL_STRUCTURE_TYPE_ENGINE_VK_SUPPORT,
} MentalStructureType;

#endif // mental_types_h